// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCertificate = "certificate"

// Certificate mapped from table <certificate>
type Certificate struct {
	ID       uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CertCode string `gorm:"column:cert_code;not null" json:"certCode"`
	CertName string `gorm:"column:cert_name;not null" json:"certName"`
}

// TableName Certificate's table name
func (*Certificate) TableName() string {
	return TableNameCertificate
}
