// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCollege = "college"

// College mapped from table <college>
type College struct {
	ID          uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CollegeCode string `gorm:"column:college_code;not null" json:"collegeCode"`
	CollegeName string `gorm:"column:college_name;not null" json:"collegeName"`
}

// TableName College's table name
func (*College) TableName() string {
	return TableNameCollege
}
