// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWorker = "worker"

// Worker mapped from table <worker>
type Worker struct {
	ID          uint32    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SecurityNo  string    `gorm:"column:security_no;not null" json:"securityNo"`
	WorkerName    string    `gorm:"column:real_name;not null" json:"workerName"`
	BirthAt     time.Time `gorm:"column:birth_at;not null" json:"birthAt"`
	GraduatedAt time.Time `gorm:"column:graduated_at;not null" json:"graduatedAt"`
	CollegeID   int32     `gorm:"column:college_id;not null" json:"collegeId"`
}

// TableName Worker's table name
func (*Worker) TableName() string {
	return TableNameWorker
}
